name: App With Github Actions with ArgoCD

on:
  workflow_dispatch
  # push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Make application.properties
      run: |
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES }}" > ./application.properties
      shell: bash

    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml

    - name: Naming jar file
      run: mv ./target/*.jar ./target/app.jar

    - name: Check jar file
      run: ls ./target

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./target/*.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set SHORT_SHA env
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.SHORT_SHA }}

  cd:
    runs-on: ubuntu-latest

    needs: ci

    steps:
    - uses: actions/checkout@v4
      with:
        repository: HeoJunHyoung/app-with-argocd-manifest
        ref: main
        token: ${{ secrets.GH_TOKEN }}

    - name: Set SHORT_SHA env
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    # ================================== 
    # 이미지 태그 업데이트 - 두 가지 방법  
    # ================================== 

    #- name: Update image tag with sed
    #  run: |
    #    sed -i "s/newTag: \".*\"/newTag: \"${{ env.SHORT_SHA }}\"/" ./manifest/overlays/dev/kustomization.yaml

    - name: Update image tag with kustomize edit
      run: |
        cd app-with-argocd-manifest/manifest/overlays/dev
        kustomize edit set image h6bro/app-with-argocd-integrated=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.SHORT_SHA }}

    - name: Commit and push changes
      run: |
        git config --local user.email "gjwnsgud4016@gmail.com"
        git config --local user.name "HeoJunHyoung"
        git add .
        git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
        git push
